name: YouTube Live Stream Recording

on:
  schedule:
    # This will run the workflow every hour at the start of the hour (00 minutes)
    - cron: '0 * * * *'  # Cron syntax: Run at the top of every hour
  workflow_dispatch:  # This allows you to run the workflow manually if needed

jobs:
  record_live_stream:
    runs-on: ubuntu-latest  # Choose an Ubuntu server for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your code

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg yt-dlp python3-pip
          pip3 install requests beautifulsoup4

      - name: Run recording script
        run: python3 script.py  # Runs your Python script that checks for live streams and records them
