name: YouTube Live Stream Recording

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the top of the hour
  workflow_dispatch:  # Allows you to run the workflow manually if needed

jobs:
  record_live_stream:
    runs-on: ubuntu-latest  # Choose an Ubuntu server for this job

    steps:
      # Checkout the repository to get all files in the correct path
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg yt-dlp python3-pip
          pip3 install requests beautifulsoup4

      # Verify the location of script.py
      - name: Verify script location
        run: |
          echo "Listing files in the repository:"
          ls -alh  # List the files in the current directory

      # Run the Python script
      - name: Run recording script
        run: python3 script.py  # Run the Python script from the root directory
