name: YouTube Live Stream Recording

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the top of the hour
  workflow_dispatch:  # Allows you to run the workflow manually if needed

jobs:
  record_live_stream:
    runs-on: ubuntu-latest  # Choose an Ubuntu server for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your code

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg yt-dlp python3-pip
          pip3 install requests beautifulsoup4

      - name: Run recording script
        run: |
          echo "Listing files in the directory to verify the presence of script.py:"
          ls -alh  # This will list all files in the directory and confirm if script.py is present
          python3 script.py  # Ensure that script.py is in the root of the repository
