name: YouTube Live Stream Recording

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python3 script.py
      continue-on-error: true  # Continue even if the script fails

    - name: Save recordings (Always runs)
      if: always()  # This ensures it runs no matter what
      run: |
        echo "Saving recordings..."
        
        # Ensure recordings are copied to the root directory
        cp -r recordings/* .

        # Add and commit any new recordings to the repository
        git config --global user.email "your_email@example.com"
        git config --global user.name "Your Name"
        
        git add .
        git commit -m "Add new recordings" || echo "No recordings to commit"
        git push origin main || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub's token to commit
