name: YouTube Live Stream Recording

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: at the correct path.

2. **Update the job definition Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup**: If the script is located in a different directory-python@v2
      with:
        python-version: '3, update the workflow file to reflect the correct path.

Here is an example of how to check the current directory and ensure the correct path in the workflow:

```yaml.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip
jobs:
  build:
    runs-on: ubuntu-latest
    steps install -r requirements.txt

    - name: Run script
      run: python3 script.py
